<div class="line3 frame white2">
			<img class="avatar-com" src="https://dl.dropboxusercontent.com/u/55281030/Xawirses.png" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=Xawirses"><strong>Xawirses</strong></a>
					, le <i>25/01/15 18:44</i>
				</p>
				<div class="line2">
					<p>zearez ar ezar</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="https://dl.dropboxusercontent.com/u/55281030/Xawirses.png" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=Xawirses"><strong>Xawirses</strong></a>
					, le <i>25/01/15 19:09</i>
				</p>
				<div class="line2">
					<p>fd sgf dfgdsfg sd</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="http://upload.wikimedia.org/wikipedia/en/7/75/Saber.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=sebspas"><strong>sebspas</strong></a>
					, le <i>25/01/15 19:10</i>
				</p>
				<div class="line2">
					<p>Test
</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="https://dl.dropboxusercontent.com/u/55281030/Xawirses.png" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=Xawirses"><strong>Xawirses</strong></a>
					, le <i>25/01/15 19:11</i>
				</p>
				<div class="line2">
					<p>To good mon pote ;)</p>
				</div>
			</div>
		</div><!-- .frame -->