<div class="line3 frame white2">
			<img class="avatar-com" src="http://upload.wikimedia.org/wikipedia/en/7/75/Saber.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=sebspas"><strong>sebspas</strong></a>
					, le <i>25/01/15 20:06</i>
				</p>
				<div class="line2">
					<p>test</p>
				</div>
			</div>
		</div><!-- .frame -->