<div class="line3 frame white2">
			<img class="avatar-com" src="http://www.allodocteurs.fr/upload/article/8307-chaton.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=john"><strong>john</strong></a>
					, le <i>25/01/15 20:53</i>
				</p>
				<div class="line2">
					<p>coucou</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="http://www.allodocteurs.fr/upload/article/8307-chaton.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=john"><strong>john</strong></a>
					, le <i>25/01/15 21:57</i>
				</p>
				<div class="line2">
					<p>rgdrggrjjukhju</p>
				</div>
			</div>
		</div><!-- .frame -->