<div class="line3 frame white2">
			<img class="avatar-com" src="http://upload.wikimedia.org/wikipedia/en/7/75/Saber.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=sebspas"><strong>sebspas</strong></a>
					, le <i>25/01/15 19:15</i>
				</p>
				<div class="line2">
					<p>Gitan !!!</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="https://dl.dropboxusercontent.com/u/55281030/Xawirses.png" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=Xawirses"><strong>Xawirses</strong></a>
					, le <i>25/01/15 19:16</i>
				</p>
				<div class="line2">
					<p>du web !!</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="https://dl.dropboxusercontent.com/u/55281030/Xawirses.png" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=Xawirses"><strong>Xawirses</strong></a>
					, le <i>25/01/15 19:23</i>
				</p>
				<div class="line2">
					<p><b>test</b></p>
				</div>
			</div>
		</div><!-- .frame -->