<div class="line3 frame white2">
			<img class="avatar-com" src="http://www.allodocteurs.fr/upload/article/8307-chaton.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=john"><strong>john</strong></a>
					, le <i>25/01/15 21:13</i>
				</p>
				<div class="line2">
					<p>gitan</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="http://www.allodocteurs.fr/upload/article/8307-chaton.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=john"><strong>john</strong></a>
					, le <i>25/01/15 21:33</i>
				</p>
				<div class="line2">
					<p>rgdgrrg</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="http://www.allodocteurs.fr/upload/article/8307-chaton.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=john"><strong>john</strong></a>
					, le <i>25/01/15 21:38</i>
				</p>
				<div class="line2">
					<p>rgrgrgr</p>
				</div>
			</div>
		</div><!-- .frame -->