<div class="line3 frame white2">
			<img class="avatar-com" src="http://s3.amazonaws.com/37assets/svn/765-default-avatar.png" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=TartineMaster"><strong>TartineMaster</strong></a>
					, le <i>31/01/15 14:46</i>
				</p>
				<div class="line2">
					<p>t'es moche ouech</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="http://upload.wikimedia.org/wikipedia/en/7/75/Saber.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=sebspas"><strong>sebspas</strong></a>
					, le <i>31/01/15 14:47</i>
				</p>
				<div class="line2">
					<p>coyucou !!!
</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="http://upload.wikimedia.org/wikipedia/en/7/75/Saber.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=sebspas"><strong>sebspas</strong></a>
					, le <i>03/02/15 18:25</i>
				</p>
				<div class="line2">
					<p>test</p>
				</div>
			</div>
		</div><!-- .frame -->