<div class="line3 frame white2">
			<img class="avatar-com" src="http://www.allodocteurs.fr/upload/article/8307-chaton.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=john"><strong>john</strong></a>
					, le <i>25/01/15 19:11</i>
				</p>
				<div class="line2">
					<p>Tu es un gitan !</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="http://upload.wikimedia.org/wikipedia/en/7/75/Saber.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=sebspas"><strong>sebspas</strong></a>
					, le <i>25/01/15 19:16</i>
				</p>
				<div class="line2">
					<p>Non c'est toi !</p>
				</div>
			</div>
		</div><!-- .frame --><div class="line3 frame white2">
			<img class="avatar-com" src="http://www.allodocteurs.fr/upload/article/8307-chaton.jpg" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=john"><strong>john</strong></a>
					, le <i>25/01/15 19:22</i>
				</p>
				<div class="line2">
					<p>non !</p>
				</div>
			</div>
		</div><!-- .frame -->