<div class="line3 frame white2">
			<img class="avatar-com" src="https://dl.dropboxusercontent.com/u/55281030/Xawirses.png" alt="default">
			<div class="inline-block vt-top">
				<p class="line2">
					<a class="txt-dec-none c-black1" href="index.php?page=profil&amp;nom=Xawirses"><strong>Xawirses</strong></a>
					, le <i>25/01/15 19:27</i>
				</p>
				<div class="line2">
					<p>Et toi à quoi tu joue ?</p>
				</div>
			</div>
		</div><!-- .frame -->